---
- name: Common tasks
  hosts: "{{ group }}"
  gather_facts: no
  vars:
    - group: common
  roles:
    - name: Update S.O. and support ansible automation
      role: common
      tags: "{{ group }}"

- name: Vault "{{ group }}" tasks
  hosts: "{{ group }}"
  gather_facts: yes
  become: yes
  vars:
    - group: unseal_cluster
  roles:
    - name: Create a vault unseal "{{ group }}"
      role: vault
      tags: "{{ group }}"

- name: Vault "{{ group }}" tasks
  hosts: "{{ group }}"
  gather_facts: yes
  become: yes
  vars:
    - group: primary_cluster
  roles:
    - name: Create a vault "{{ group }}"
      role: vault
      tags: "{{ group }}"
