---
- name: Common tasks
  hosts: "{{ group }}"
  gather_facts: no
  vars:
    - group: common
  roles:
    - name: Update S.O. and support ansible automation
      role: common
      tags: "{{ group }}"

- name: Vault autounseal cluster tasks
  hosts: "{{ group }}"
  gather_facts: yes
  become: yes
  vars:
    - group: autounseal_cluster
  roles:
    - name: Create a vault cluster
      role: vault
      tags: "{{ group }}"

- name: Vault primary cluster tasks
  hosts: "{{ group }}"
  gather_facts: yes
  become: yes
  vars:
    - group: primary_cluster
  roles:
    - name: Create a vault cluster
      role: vault
      tags: "{{ group }}"
