---
- name: Destroy current vault - WARNING
  shell: "systemctl stop vault || true && systemctl disable vault || true && rm -rf {{ install_path }} /usr/lib/systemd/system/vault || true"
  when: destroy_first is defined and destroy_first == true

- name: Add vault user
  ansible.builtin.user:
    name: vault
    system: yes
    shell: /sbin/nologin
    group: vault
    state: present

- name: Create install directory tree
  file:
    path: "{{ item }}"
    state: directory
    recurse: yes
    owner: vault
    group: vault
    mode: 0700
  loop:
    - "{{ install_path }}/bin"
    - "{{ install_path }}/data"
    - "{{ install_path }}/conf/certs"
    - "{{ install_path }}/log"

- name: Create vault config
  ansible.builtin.template:
    src: vault.hcl.j2
    dest: "{{ install_path }}/conf/vault.hcl"
    owner: vault
    group: vault
    mode: 0600

- name: Create environment file
  ansible.builtin.template:
    src: vault.env.j2
    dest: "{{ install_path }}/conf/vault.env"
    owner: vault
    group: vault
    mode: 0600

- name: Copy vault binary
  copy:
    src: vault
    dest: "{{ install_path }}/bin/"
    owner: vault
    group: vault
    mode: 0700

- name: Copy certificates for tls communication
  copy:
    src: "{{ item }}"
    dest: "{{ install_path }}/conf/certs/"
    owner: vault
    group: vault
    mode: 0600
  loop:
    - "{{ tls_name }}.crt"
    - "{{ tls_name }}.key"
    - rootCA.crt
  when: tls_name is defined

- name: Create vault service
  ansible.builtin.template:
    src: vault.service.j2
    dest: "/usr/lib/systemd/system/vault.service"
    owner: vault
    group: vault
    mode: 0600

- name: Enable service vault
  ansible.builtin.systemd:
    name: vault
    enabled: yes
    masked: no
    state: restarted
    daemon_reload: yes
    force: yes
